### ISSUE TITLE
Eaditor/Admin/ Error Unauthorized User, Yet settings allow collection editing

### ISSUE THREAD

**Issue by podengo** [ewg118/eaditor#30]
I managed to create my first collection with the Eaditor a couple of days ago, by logging in as a tomcat user with roles "orbeon-user,eaditor-admin" and filling out the sequence of forms that automatically appeared. Yay!
However, sadly, now whenever I revisit .../eaditor/admin/ and login as a tomcat user with roles orbeon-user,eaditor-admin, I see a page with:

------------

The top has row has three links: "EADitor Admin", "Admin Home" and "Modify Settings"
The rest of the page is only this message: 

Unauthorized User
You are seeing this interface either because authentication has not been enabled for the EADitor administrative panel or there is no matching eXist-db collection for your role. If it is the latter case, please log in as the eaditor-admin role and create a new collection for the associated Tomcat role.
----------

Also, when I do hit the "Modify Settings" link, I go to a nice page that lets me edit and save the settings for my initial collection.

Given that, I first supposed "there is no exist-db collection for my role.", that maybe I did not create the initial collection correctly, or maybe I failed to save it.

When I go to the 'exist' url on my tomcat site, it insists on the login 'admin' and does not allow my normal tomcat login that has the eaditor-admin role. (Maybe that's a factor here?)

When I see the initial 'eXist' page, after I login as 'admin', then when I click on eXide icon and next on the 'directory' tab, the tree on the left shows root node "db" with three sub-folders: apps, eaditor, and system, and I can expand the eaditor node and see various files and edit them fine with the eXide application. 

So my problem now is still with revisting my .../eaditor/admin/  page: 

What do I do to "log in as the eaditor-admin role and create  a new collection"? Also what is the 'associated Tomcat role' being referred to in the message?

Thanks in advance for your help.

**Comment by podengo** [comment]
Sorry, again with the large font. I promise it all looks normal, but only after I hit submit and revisit my own comment do I see that... I probably need to read up on github comment editing...

**Comment by ewg118** [comment]
There could be a few factors: is the 'orbeon-user' Tomcat role also assigned to a user that has access to a collection. There can be at most one role assigned to EADitor users within the EADitor webapp.

The eXist admin account and password are inherent to the eXist webapp, and are not connected to Tomcat's authentication configuration (that are used for Orbeon). By default, eXist has an administrative account with the username 'admin' and a blank password. If you have changed this password, then the exist-config.xml needs to be updated with the password. There are instructions at https://github.com/ewg118/eaditor/wiki/Deploying-eXist

There should also be one role defined in the tomcat-users.xml for your eXist collection (I prefer to keep the role name and collection name the same), and at least one user connected to this role. I usually use MARC codes for collection names, since they are unique for an institution.

E.g.,

`<role rolename="eaditor-admin"/>`
`<role rolename="nnan"/>`
`<user username="egruber" password="" roles="eaditor-admin"/>`
`<user username="numishare-test" password="" roles="nnan"/>`

Your web.xml for Orbeon should have something like this:

        <security-constraint>
                <web-resource-collection>
                        <web-resource-name>EADitor Admin</web-resource-name>
                        <url-pattern>/eaditor/admin/*</url-pattern>
                </web-resource-collection>
                <auth-constraint>
                        <role-name>eaditor-admin</role-name>
                        <role-name>nnan</role-name>
                </auth-constraint>
        </security-constraint>

**Comment by podengo** [comment]
Thank you for all your tips and attention. However, I made sure our system complies with your suggestions, and the behavior I reported is unchanged for new logins with only the eaditor-admin role.
It's been a few days, and I just wanted to get back to you and thank you.
 
We may have time later to delve into it again and generate new questions or data about our system that may help to diagnose this.

**Comment by ewg118** [comment]
To follow up on this old issue, can you tell me what version of Orbeon you are using? There has been some change in authentication in Orbeon 2016.x vs. 4.10 (December 2015).

**Comment by ewg118** [comment]
The original issue should be fixed.
