### ISSUE TITLE
Cannot add multiple creators

### ISSUE THREAD

**Issue by jenpalmentiero** [ewg118/eaditor#39]

**Comment by ewg118** [comment]
Creators of the finding aid in the EAD Header?

**Comment by jenpalmentiero** [comment]
No, there seems to be a problem with adding multiple collection creators. The problem is inconsistent, though. Sometimes after I add a Corporate name, Family Name or Personal Name creator, the choices disappear and I can't add another creator. Sometimes after saving a guide, I get the choices back, BUT when I click one of those choices to add a second creator, the first one I added disappears.

**Comment by senyzspalding** [comment]
Jen just showed this to me, I will look at it and give you some more details into the issue

**Comment by ewg118** [comment]
Okay, multiple famname/corpname/persname elements are possible in origination. Note that when importing finding aids created outside EADitor that have an origination with just a textual input (no nested personal, corporate, or family names), this free text will be deleted when one of these three elements is added. This is so that editors might replace unstructured names with controlled vocabulary when making updates.
