### ISSUE TITLE
"Expand" link not working consistently 

### ISSUE THREAD

**Issue by jenpalmentiero** [ewg118/eaditor#46]
The Expand link is not working consistently in the EADitor admin panel.

**Comment by ewg118** [comment]
Something in the orbeon code is malfunctioning, and the code I previously wrote no longer works. I am still troubleshooting, but have removed the "expand" link in the mean time.

**Comment by ewg118** [comment]
Okay, I finally tracked down the issue here relating to the jQuery javascript library and Orbeon. It is detailed here: http://blog.orbeon.com/2015/05/namespacing-jquery.html. It involved updating the javascript for the expand/collapse components button in EADitor as well as deploying Orbeon 4.10 (December 2015), which is at least two years more recent than what had previously been deployed on empireadc.org. This may end up fixing other miscellaneous glitches.
